apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: data-ingestion-service
  namespace: '366008494339'
  selfLink: >-
    /apis/serving.knative.dev/v1/namespaces/366008494339/services/data-ingestion-service
  uid: 987c136e-0b12-450f-bd3a-775ad384911e
  resourceVersion: AAY5rHS9jr0
  generation: 23
  creationTimestamp: '2025-07-08T17:01:58.557980Z'
  labels:
    commit-sha: 9e125ea9144c0afe03c73a95d799e35db18c534d
    gcb-build-id: 65c6af81-c049-449d-94a0-8a9ad35ff1af
    gcb-trigger-id: 2a51b7f7-828e-4c21-bd6e-51801ef3a395
    gcb-trigger-region: global
    managed-by: gcp-cloud-build-deploy-cloud-run
    run.googleapis.com/satisfiesPzs: 'true'
    cloud.googleapis.com/location: asia-southeast1
  annotations:
    serving.knative.dev/creator: qbao2805@gmail.com
    serving.knative.dev/lastModifier: qbao2805@gmail.com
    run.googleapis.com/client-name: cloud-console
    run.googleapis.com/operation-id: 842fafdf-58d1-4865-8920-9600393c1207
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/urls: >-
      ["https://data-ingestion-service-366008494339.asia-southeast1.run.app","https://data-ingestion-service-ud5pi5bwfq-as.a.run.app"]
spec:
  template:
    metadata:
      labels:
        client.knative.dev/nonce: gvtreeuqtq
        commit-sha: 9e125ea9144c0afe03c73a95d799e35db18c534d
        gcb-build-id: 65c6af81-c049-449d-94a0-8a9ad35ff1af
        gcb-trigger-id: 2a51b7f7-828e-4c21-bd6e-51801ef3a395
        gcb-trigger-region: global
        managed-by: gcp-cloud-build-deploy-cloud-run
        run.googleapis.com/startupProbeType: Default
      annotations:
        autoscaling.knative.dev/maxScale: '10'
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 529.0.0
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 100
      timeoutSeconds: 300
      serviceAccountName: data-ingestion-sa@competitor-destroyer.iam.gserviceaccount.com
      containers:
      - image: >-
          asia-southeast1-docker.pkg.dev/competitor-destroyer/cloud-run-source-deploy/data-processing-service/data-ingestion-service:9e125ea9144c0afe03c73a95d799e35db18c534d
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: BRIGHTDATA_API_KEY
          valueFrom:
            secretKeyRef:
              key: latest
              name: brightdata-api-key
        - name: GOOGLE_CLOUD_PROJECT
          value: competitor-destroyer
        - name: BIGQUERY_DATASET
          value: social_analytics
        - name: PUBSUB_TOPIC_PREFIX
          value: social-analytics
        - name: GCS_BUCKET_RAW_DATA
          value: social-analytics-raw-data
        - name: APIFY_API_TOKEN
          valueFrom:
            secretKeyRef:
              key: latest
              name: apify-api-token
        - name: BACKGROUND_POLLING_ENABLED
          value: "true"
        - name: BACKGROUND_MAX_WORKERS
          value: "10"
        - name: BACKGROUND_POLL_INTERVAL
          value: "30"
        - name: BACKGROUND_MAX_POLLS
          value: "120"
        - name: BACKGROUND_DOWNLOAD_TIMEOUT
          value: "300"
        resources:
          limits:
            cpu: '1'
            memory: 1Gi
        startupProbe:
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
          tcpSocket:
            port: 8080
  traffic:
  - revisionName: data-ingestion-service-00011-7np
    percent: 100
